site_name: My Docs
site_url: https://breakpoint7.github.io/testdocs/
nav:
  - Home: index.md
  - Page2: page2.md
  - Section1:
    - Subpage1: subpage1.md
    - Subpage2: subpage2.md
theme:
  name: material
